version: '3'

services: 
    mongo-db:
        container_name: mongo-db
        image: mongo
        ports: 
            - "27017:27017"
        restart: always
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes: 
            - /local_path:/docker_path
        